server:
  port: 8762  # Porta padrão para o Eureka Server

eureka:
  client:
    registerWithEureka: false  # O servidor não se registra como um cliente
    fetchRegistry: false  # Não precisa buscar informações do registro
