server:
  port: 8761  # Porta padrão para o Eureka Server

eureka:
  client:
    registerWithEureka: false  # O servidor não se registra como um cliente
    fetchRegistry: false  # Não precisa buscar informações do registro
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
